import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np
import time
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split

class LoadData:
    def __init__(self, path):

        """Most of the init function is generated by ChatGPT, as I didn't know how to exactly preprocess this data.
        In this instance, we can classifiy categorical and numeric variables independently, and apply different preprocessing steps to each.
        Additionally, this converts the data into a numeric format for the LSTM processing 
        """

        # Load CSV
        self.df = pd.read_csv(path)
        print("\nRaw Data Loaded:")
        print(self.df.head())

        # Replace empty strings with NaN
        self.df.replace(r'^\s*$', np.nan, regex=True, inplace=True)

        # Define categorical and numeric columns
        self.cat_cols = [
            'gender', 'dementia', 'dementia_all', 'diabetes', 'hypertension',
            'hypercholesterolemia', 'smoking', 'Lacunes_Presence',
            'CMB_Presence', 'fazekas_cat', 'study_Name'
        ]
        self.num_cols = [
            'age', 'EF', 'PS', 'Global', 'SVD Simple Score',
            'SVD Amended Score', 'lac_count'
        ]

        # Fill categorical NaNs and encode
        self.label_encoders = {}
        for col in self.cat_cols:
            self.df[col] = self.df[col].fillna("Unknown").astype(str)
            le = LabelEncoder()
            self.df[col] = le.fit_transform(self.df[col])
            self.label_encoders[col] = le

        # Convert numeric columns to float
        self.df[self.num_cols] = self.df[self.num_cols].apply(pd.to_numeric, errors='coerce')

        # Fill NaNs with column mean or 0 if entire column is NaN
        for col in self.num_cols:
            if self.df[col].isna().all():
                self.df[col] = 0.0
            else:
                self.df[col] = self.df[col].fillna(self.df[col].mean())

        # Normalize numeric columns
        self.df[self.num_cols] = MinMaxScaler().fit_transform(self.df[self.num_cols])

        print("\nCleaned and Encoded Data:")
        print(self.df.head())

    def get_tensors(self, target_col='dementia'):
        # Target variable: binary
        y = (self.df[target_col] > 0).astype(int).values
        X = self.df.drop(columns=[target_col]).values

        # Ensure finite and in [0,1]
        X = np.nan_to_num(X, nan=0.0)
        X = np.clip(X, 0, 1)

        # Reshape for LSTM: (samples, seq_len=1, features)
        X = np.expand_dims(X, axis=1)

        # Train/test split
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )

        # Convert to PyTorch tensors
        X_train = torch.tensor(X_train, dtype=torch.float32)
        y_train = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)
        X_test = torch.tensor(X_test, dtype=torch.float32)
        y_test = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)

        return X_train, X_test, y_train, y_test
    
class DementiaRiskLSTM(nn.Module): # here, we initialize an lstm 
    def __init__(self, input_size, hidden_size, num_layers=1):
        super(DementiaRiskLSTM, self).__init__()
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, x):
        out, _ = self.lstm(x)
        out = out[:, -1, :]
        out = self.fc(out)
        out = self.sigmoid(out)
        return out

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def train_model(model, X_train, y_train, X_test, y_test, num_epochs=30, lr=1e-3):
    model.to(device)
    criterion = nn.BCELoss()  # For binary classification
    optimizer = optim.Adam(model.parameters(), lr=lr)

    start_time = time.time()
    for epoch in range(num_epochs):
        model.train()
        optimizer.zero_grad()

        inputs = X_train.to(device)
        labels = y_train.to(device)

        outputs = model(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # Train accuracy
        preds = (outputs > 0.5).float()
        acc = (preds == labels).float().mean()

        if epoch % 5 == 0:
            print(f"Epoch [{epoch+1}/{num_epochs}] - Loss: {loss.item():.4f} - Train Acc: {acc.item()*100:.2f}%")

    end_time = time.time()
    print(f"\nTraining finished in {(end_time - start_time)/60:.2f} minutes")

    # Evaluate on train set
    model.eval()
    with torch.no_grad():
        train_outputs = model(X_train.to(device))
        train_preds = (train_outputs > 0.5).float()
        train_acc = (train_preds == y_train.to(device)).float().mean()
        print(f"Final Train Accuracy: {train_acc.item()*100:.2f}%")

        # Evaluate on test set
        test_outputs = model(X_test.to(device))
        test_preds = (test_outputs > 0.5).float()
        test_acc = (test_preds == y_test.to(device)).float().mean()
        print(f"Test Accuracy: {test_acc.item()*100:.2f}%")

        # Classification report
        y_true = y_test.cpu().numpy()
        y_pred = test_preds.cpu().numpy()
        print("\nClassification Report:\n", classification_report(y_true, y_pred, target_names=["No Dementia", "Dementia"], zero_division=0))


def main():
    data = LoadData("BMData/patient_records.csv")
    X_train, X_test, y_train, y_test = data.get_tensors()

    input_size = X_train.shape[2]
    model = DementiaRiskLSTM(input_size=input_size, hidden_size=32)

    train_model(model, X_train, y_train, X_test, y_test, num_epochs=30, lr=1e-3)

if __name__ == "__main__":
    main()